version: '3'
services:
  app:
    build:
      context: ./docker/app
    volumes:
      - ./html:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Asia/Tokyo
      HOST_REPOSITORY_ROOTDIR: ${PWD}
    ports:
      - 80:80
